server:
  port: 80

#配置spring的连接
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hw_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B0

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true

#配置pagehelper的内容
pagehelper:
  helper-dialect: mysql