server:
  port: 8080

#配置spring的连接
spring:
  datasource:
    username: root
    password: FHI%*#5843
    url: jdbc:mysql://10.110.145.36:30005/idb_dm_catalog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true

#配置pagehelper的内容
pagehelper:
  helper-dialect: mysql